#include "../include/constants.h"

    apSetter_t RAARR[] = {
      APSET_ITEM,      
      APSET_ITEM_NEXT,
      APSET_ITEM_PREV,
      APSET_ITEM_RND,     
      APSET_PLAY_START,
      APSET_PLAY_STOP,
      APSET_PLAY_PAUSE,    
      APSET_PLAY_TOGGLE,     
      APSET_PLAY_DELAY,
      APSET_PLAY_DELAYMIN,
      APSET_PLAY_DELAYMINON, 
      APSET_PLAY_DELAYMINOFF,
      APSET_PLAY_RND,       
      APSET_PLAY_PL,       
      APSET_PLAY_LB,       
      APSET_PLAY_LT,
      APSET_LSET_PL,
      APSET_LSET_PLNEXT,
      APSET_LSET_PLPREV,       
      APSET_LSET_PLRND,       
      APSET_LSET_LB,     
      APSET_LSET_LBNEXT,     
      APSET_LSET_LBPREV,     
      APSET_LSET_LBRND,
      APSET_PLI_NEW,
      APSET_PLI_REM,
      APSET_PLI_REP,
      APSET_PL_TOFS,
      APSET_ITEMID
    };